version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: economarket
    container_name: economarket_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: economarket_adminer
